### ISSUE TITLE
TreeMap chart crash

### ISSUE THREAD

**Issue by yvelianyk** [amcharts/amcharts4#1125]
It appears in the case when the chart is drilled down into some section and new data set is applied to it. 
Chart tries to redraw itself and after that, it crashes with the message 'EventDispatcher is disposed'. It does not happen every time. Usually, it happens after the second or third attempt. 
Also, you can easily reproduce it on the fiddle which I provided. For reproducing, just try to click on some square(drill down) to one or two deep levels, after some number of attempts the chart is crashed. 
Also, the crash does not appear when the chart is not drilled down.
Here is the [jsFiddle](http://jsfiddle.net/yvelianyk/ag6n7w92/15/) where you can easily reproduce it.

Here are the screenshot
![CrashChart](https://user-images.githubusercontent.com/17911345/55223022-f2a1ed80-5215-11e9-8867-9f01d1e6dfe6.png)

**Comment by martynasma** [comment]
Fixed in [4.3.6](https://github.com/amcharts/amcharts4/releases/tag/4.3.6).

## [4.3.6] - 2019-04-04

### Added
- New `DateFormatter` property: `timezoneOffset`. Set it to a number of minutes (to UTC) to recalculate all date/time to a specific time zone.

### Changed
- `DateFormatter` will now use locale information for its default date format set in `dateFormat`. Format in default "International English" locale did not change, and remains at `"yyyy-MM-dd"`. Other locales might or might not produce different date formats.
- Improved `ValueAxis` scale calculation algorithm when `min`/`max` is set.
- `"hit"` event is now added on `FlowDiagramNode` template instead of the class itself. This allows disabling default toggle/drag behavior and replacing with own events.

### Fixed
- Themes were not properly being applied to bullets.
- `Popup.draggable` was being ignored.
- `Series.legendSettings.itemValueText` was being ignored when `cursorTooltipEnabled = false`. #1141
- Mouse events over `LineSeries` segments where happening at wrong position.
- `legend.valueLabels` on `TreeMap` did not work.
- Changing Map projection with `panBehavior = "rotateLongLat"` could cause a JS error.
- Changing `TreeMap` data after chart size changed could cause zoom-out button to appear.
- Solved flickering of stacked columns when raw data was invalidated.
- Updating data of a `TreeMap` when animation was playing could result in a JS error.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by yvelianyk** [comment]
Hi guys.
I see that you fixed chart crash.

> Updating data of a TreeMap when animation was playing could result in a JS error.

But I still can reproduce it in the case when the animation is disabled. So I suppose the root of the chart crash problem is not in the playing animation. We use this chart without animation except for some manually enabled effects so it is still reproducible.
![AmchartsCrash2](https://user-images.githubusercontent.com/17911345/55945119-d7da6a80-5c52-11e9-9fc5-30904f086a96.png)

Also, you can easy reproduce it on this [fiddle](http://jsfiddle.net/yvelianyk/dne6shLw/8/)

Thanks.
