### ISSUE TITLE
FontAwesome icons can't be exported or printed

### ISSUE THREAD

**Issue by sambakk** [amcharts/amcharts4#1758]
Please, why when I export a chart in PDF or image formats or even when I print, the fontAwesome icons don't appear ?

**Comment by martynasma** [comment]
Unfortunately, browsers would not allow including images loaded from different domain than the page displaying the chart. There is no way around it - it's a built-in security precaution.

I'm not too familiar with FA. Maybe they have an option to host font files or images on the same host as the web page? That should solve the issue.

**Comment by martynasma** [comment]
Yes.

**Comment by sambakk** [comment]
@martynasma, I use icons from my local, but still not shown when the chart is printed or exported!

**Comment by martynasma** [comment]
Would you be able to post your chart online where we can check?

**Comment by sambakk** [comment]
Here's a snippet of my code, I use local icons inside my project in amchart 4 categoryAxis html title : 

```js

   // Create chart
    var chart = am4core.create(div_id, am4charts.XYChart);
    chart.zoomOutButton.disabled = true;

    // Add data
    chart.data = data;
    chart.colors.list = colors;

    // Create axes
    var categoryAxis = chart.yAxes.push(new am4charts.CategoryAxis());
    categoryAxis.dataFields.category = "category";
    categoryAxis.renderer.labels.template.disabled = true;
    categoryAxis.renderer.grid.template.disabled = true;
    categoryAxis.renderer.cellStartLocation = 0.2;
    categoryAxis.renderer.cellEndLocation = 0.8;
    categoryAxis.title.html =
        "<div class='icons-on-charts mb-3'><img class='img-fluid' src='assets/icons/img1.png' ></div>" +
        "<div class='icons-on-charts mt-3'><img class='img-fluid' src='assets/icons/img2.png' ></div>";
    categoryAxis.title.rotation = 0;
    categoryAxis.title.marginRight = 20;
```

**Comment by martynasma** [comment]
OK, so HTML content won't get exported, I'm afraid.

In labels, HTML content is implemented via `foreignObject` SVG tag, which does not export to canvas.

There's no way around it, I'm afraid.

If you need those images in the title, I suggest you create them as children axis.title. Something like this:

```
var img1 = cateoryAxis.title.createChild(am4core.Image);
img1.href = 'assets/icons/img1.png';
```

**Comment by sambakk** [comment]
I tried the following code after creating the category axis, but It doesn't show anything on the chart

```js
var img1 = categoryAxis.title.createChild(am4core.Image);
    img1.href = 'assets/icons/img1.png';
    img1.width = 150;
    img1.height = 150;
```

**Comment by martynasma** [comment]
OK, adding images to title is a bit overkill. Why not create images directly in `bottomAxesContainer`?

```
var img1 = chart.bottomAxesContainer.createChild(am4core.Image);
img1.href = 'assets/icons/img1.png';
img1.width = 150;
img1.height = 150;
img1.align = "center";
```

**Comment by sambakk** [comment]
It works, but it shows icons in the **bottom of the chart**, I want them on the left, that's way I want to put them besides the category axis which is on the left

**Comment by martynasma** [comment]
In that case you should use `leftAxesContainer` :)

**Comment by sambakk** [comment]
Thank you very much @martynasma
