### ISSUE TITLE
Chart & legend captures scrolling (with mouse-wheel or on touch device)

### ISSUE THREAD

**Issue by Chnoch** [amcharts/amcharts4#388]
Charts and legends (either within the chart container or in a separate container) capture scroll events with the mouse-wheel or on a touch device, so that one can only scroll when the mouse or touch target is outside the chart/legend container. 
Is there a setting to disable the full capturing of scroll events or could this be added?

**Comment by martynasma** [comment]
Yes:

```
chart.mouseWheelBehavior = "none";
```

https://www.amcharts.com/docs/v4/reference/xychart/#mouseWheelBehavior_property

Hope this is what you were looking for.

**Comment by Chnoch** [comment]
Thanks for your quick reply. I've already set `mouseWheelBehavior` to `none`, however this is not exactly what I'm looking for. There's no longer interaction with the chart (which is good), however it still doesn't scroll the page when using the scroll wheel or a touch device while the mouse/touch target is within the chart. It captures and ignores the event.
I can code up a small codepen tomorrow to show the behavior

**Comment by martynasma** [comment]
That's weird. If wheel behavior is set to "none" it should not interfere with scrolling anymore

Yes, codepen example would help. Thanks!

**Comment by Chnoch** [comment]
As promised, here's a codepen: https://codepen.io/chnoch/pen/ZMdeEm

When hovering over the chart and using the mouse-wheel to scroll, the page mostly stays put and doesn't scroll. Same when using a touch device such as a smartphone. I have had success when using it on a laptop with a touchpad, where scrolling works as expected. 
I hope you can reproduce the issue that I'm facing :)

**Comment by martynasma** [comment]
Thanks. Looks like elements that area "stealing" the show are axis fills. Scroll works on every second grid. I know it's weird.

We'll need to fix that on our end.

In the interim, explicitly disabling interactions on axis fills on all axes should fix the issue:

```
categoryAxis.renderer.axisFills.template.interactionsEnabled = false;
valueAxis.renderer.axisFills.template.interactionsEnabled = false;
```

**Comment by Chnoch** [comment]
Thanks for the investigation. This already helps when hovering over the empty parts of the chart, however there is still an issue when hovering over an actual entry (e.g. in the codepen provided when hovering over the big yellow column, scrolling doesn't work) or when using touch devices and trying to start to scroll over the legend is also still blocked.

Do you have an idea for a workaround for these issues? Otherwise I'll just wait until you have it properly resolved on your end.

**Comment by martynasma** [comment]
Fixed in [4.0.0-beta.56](https://github.com/amcharts/amcharts4/releases/tag/4.0.0-beta.56).

## [4.0.0-beta.56] - 2018-10-12

### Added
- New `Sprite` adapter: `"populateString"`. Applied to strings after `Sprite` replaces data binders with real values, but before any formatting by `Label` kicks in.
- New `Label` property: [`ignoreFormatting`](https://www.amcharts.com/docs/v4/reference/label/#ignoreFormatting_property). If set to `true` will treat formatting blocks in square brackes (e.g. `"[red bold]"`) as regular text and will display them as such.

### Changed
- Default big, small, and byte suffixes in `NumberFormatter` are now translatable via locale files.
- The suffix for thousands "kilo", was changed to lowercase "k", as per [standards](https://en.wikipedia.org/wiki/International_System_of_Units#Prefixes).
- On `XYChart`, default for [`mouseWheelBehavior`](https://www.amcharts.com/docs/v4/reference/xychart/#mouseWheelBehavior_property) changed to `"none"` (was `"zoomX"`).

### Fixed
- Improved performance! All charts types are now noticably, some drastically are faster. Some memory leakages fixed as well.
- Now `MapPolygonSeries` will not inherit chart's global `geodata` if it has own `geodataSource` set.
- `DateFormatter` was not parsing all AM/PM string dates correctly.
- `DateFormatter` was not parsing `MMM` (short month names like "Jan", "Feb") propertly.
- In-line date formatter was not working correctly in some cases, e.g. `"{dateX.formatDate()}"`.
- Setting `chart.mouseWheelBehavior = "none"` did not release wheel scrolling of the web page when hovering over chart.
- `DataSource`'s' `"done"` event was being called if parsing of loaded data failed. Not anymore. `"done"` is called only on successful load. To catch any load (including one that ended in http or parse error) use `"ended"`.
- `DataSource`'s' `reloadFrequency` was broken if error occurred during one of the loads. This has been fixed. Even if error occurrs, loader will try to reload data in the next reload slot.
- JSON: `heatRules` did not work properly with their target set to a list template, e.g. `mapPolygons.template`.
- Auto-calculated `DateAxis.baseInterval` was not being carried over to the `XYChartScrollbar`.
- `DurationAxis` scale sometimes was dropping to negative values, even there were no negative values in data.
- `PieChart` and `Legend` were not working properly with `chart.zoom()` or `legend.zoom()` methods.

[Full change log](https://github.com/amcharts/amcharts4/blob/master/dist/es2015/CHANGELOG.md).

Make sure you clear your browser cache after upgrading. And feel free to contact us again if you are still experiencing this issue.

**Comment by Chnoch** [comment]
Thanks for the update, this works fine for scrolling with a mouse wheel. 
However using a touch device such as a smartphone or tablet and starting a swipe on an item of the chart or on the legend still results in the same issue as described above. The behavior can also be reproduced on the existing codepen, just with a touch device (or with emulating the behavior using Chrome DevTools). 

Can you double-check that?

**Comment by martynasma** [comment]
Hey @Chnoch 

We're working on a fix for touch as we speak. I'm hoping we can this update out by EOW.

This is the main issue for it: #475

You might want to subscribe to it.

**Comment by Chnoch** [comment]
Thanks for linking the issue, I subscribed and will track progress on that ticket and check whether it works as expected once the fix is released.

**Comment by ahmedalashhab** [comment]
Any news on this?
