### ISSUE TITLE
reference #420, Typescript 3 errors

### ISSUE THREAD

**Issue by nKorous** [amcharts/amcharts4#611]
We are still running into the issues outlined in issue #420. The issue says it was fixed in Beta-72 but it still seems to be present in the latest version. These errors happen when starting the project in dev mode and when building (`yarn start`, `yarn run build`)

### Environment
amcharts4 = 4.0.2
Typescript = 3.1.6
React = 16.5.2

### snippet of error:
```
｢wdm｣: Compiled successfully.
ERROR in /node_modules/@amcharts/amcharts4/.internal/charts/axes/Axis.d.ts(106,5):
TS2416: Property '_component' in type 'AxisDataItem' is not assignable to the same property in base type 'DataItem'.
  Type 'Axis<AxisRenderer>' is not assignable to type 'Component'.
ERROR in /node_modules/@amcharts/amcharts4/.internal/charts/axes/Axis.d.ts(348,5):
TS2416: Property '_dataItem' in type 'Axis<T>' is not assignable to the same property in base type 'Component'.
  Type 'AxisDataItem' is not assignable to type 'DataItem'.
ERROR in /node_modules/@amcharts/amcharts4/.internal/charts/axes/AxisFill.d.ts(106,5):
TS2416: Property '_dataItem' in type 'AxisFill' is not assignable to the same property in base type 'Sprite'.
  Type 'AxisDataItem' is not assignable to type 'DataItem'.
ERROR in /node_modules/@amcharts/amcharts4/.internal/charts/axes/AxisLabel.d.ts(84,5):
TS2416: Property '_dataItem' in type 'AxisLabel' is not assignable to the same property in base type 'Label'.
  Type 'AxisDataItem' is not assignable to type 'DataItem'.
ERROR in /node_modules/@amcharts/amcharts4/.internal/charts/axes/AxisRendererCircular.d.ts(108,5):
TS2416: Property '_gridType' in type 'AxisRendererCircular' is not assignable to the same property in base type 'AxisRenderer'.
  Type 'GridCircular' is not assignable to type 'Grid'.
    Types of property 'events' are incompatible.
      Type 'SpriteEventDispatcher<AMEvent<GridCircular, IGridCircularEvents>>' is not assignable to type 'SpriteEventDispatcher<AMEvent<Grid, IGridEvents>>'.
        Types of property '_on' are incompatible.
          Type '<A, B, Key extends "resize" | "track" | "hidden" | "input" | "blur" | "drag" | "dragstart" | "focus" | "keydown" | "keypress" | "keyup" | "wheel" | "up" | "down" | "over" | "hit" | "doublehit" | "rightclick" | ... 24 more ... | "toggled">(once: boolean, type: Key | null, callback: A, context: B, shouldClone: boolean...' is not assignable to type '<A, B, Key extends "resize" | "track" | "hidden" | "input" | "blur" | "drag" | "dragstart" | "focus" | "keydown" | "keypress" | "keyup" | "wheel" | "up" | "down" | "over" | "hit" | "doublehit" | "rightclick" | ... 24 more ... | "toggled">(once: boolean, type: Key | null, callback: A, context: B, shouldClone: boolean...'. Two different types with this name exist, but they are unrelated.
            Type 'EventListener<AMEvent<GridCircular, IGridCircularEvents>>' is not assignable to type 'EventListener<AMEvent<Grid, IGridEvents>>'.
              Type 'AMEvent<Grid, IGridEvents>' is not assignable to type 'AMEvent<GridCircular, IGridCircularEvents>'.
ERROR in /node_modules/@amcharts/amcharts4/.internal/charts/axes/AxisRendererCircular.d.ts(114,5):
TS2416: Property '_fillType' in type 'AxisRendererCircular' is not assignable to the same property in base type 'AxisRenderer'.
  Type 'AxisFillCircular' is not assignable to type 'AxisFill'.
    Types of property 'events' are incompatible.
      Type 'SpriteEventDispatcher<AMEvent<AxisFillCircular, IAxisFillCircularEvents>>' is not assignable to type 'SpriteEventDispatcher<AMEvent<AxisFill, IAxisFillEvents>>'.
        Types of property '_on' are incompatible.
          Type '<A, B, Key extends "resize" | "track" | "hidden" | "input" | "blur" | "drag" | "dragstart" | "focus" | "keydown" | "keypress" | "keyup" | "wheel" | "up" | "down" | "over" | "hit" | "doublehit" | "rightclick" | ... 24 more ... | "toggled">(once: boolean, type: Key | null, callback: A, context: B, shouldClone: boolean...' is not assignable to type '<A, B, Key extends "resize" | "track" | "hidden" | "input" | "blur" | "drag" | "dragstart" | "focus" | "keydown" | "keypress" | "keyup" | "wheel" | "up" | "down" | "over" | "hit" | "doublehit" | "rightclick" | ... 24 more ... | "toggled">(once: boolean, type: Key | null, callback: A, context: B, shouldClone: boolean...'. Two different types with this name exist, but they are unrelated.
            Type 'EventListener<AMEvent<AxisFillCircular, IAxisFillCircularEvents>>' is not assignable to type 'EventListener<AMEvent<AxisFill, IAxisFillEvents>>'.
              Type 'AMEvent<AxisFill, IAxisFillEvents>' is not assignable to type 'AMEvent<AxisFillCircular, IAxisFillCircularEvents>'.
```

**Comment by nKorous** [comment]
@Pauan 
Thanks for the prompt reply. I have not added those to the `tsconfig.json` as both of those checks are required for this project. I did see that article on the support site, but going off the comments in #420 it seemed as though this was fixed (and not just a work around).

**Comment by Pauan** [comment]
@nKorous They are two different issues:

* #420 is about TypeScript 3 support (which has been fully fixed)

* The errors you are getting are about TypeScript strict mode (which affects both TypeScript 2 and TypeScript 3). That is being tracked at #72 

   We know that this is a big deal, and we are working on it, but AmCharts 4 was written before strict mode existed, so it's a lot of work to change our code to be strict mode compatible.

If you want to enable strict mode support for your project while still using AmCharts, you can use `as any` to selectively disable type checking for the specific parts which are causing errors:

```ts
let dateAxis = chart.xAxes.push(new am4charts.DateAxis() as any);
let valueAxis = chart.yAxes.push(new am4charts.ValueAxis() as any);
let series = chart.series.push(new am4charts.LineSeries() as any);
chart.scrollbarX = scrollbarX as any;
```

**Comment by Hlakaza** [comment]
@kishandonepudi use @Pauan answer that worked for me 

let  dateAxis = chart.xAxes.push(new am4charts.DateAxis() as any);
let valueAxis = chart.yAxes.push(new am4charts.ValueAxis() as any);
let series = chart.series.push(new am4charts.LineSeries() as any);
chart.scrollbarX = scrollbarX as any;

**Comment by Pauan** [comment]
@kishandonepudi Angular 5 is pretty old, we recommend upgrading to the latest Angular.

Assuming that you are not able to upgrade, you should add this to your `tsconfig.json`:

```json
{
  "compilerOptions": {
    "strictNullChecks": false,
    "strictFunctionTypes": false
  }
}
```

If even *that* doesn't work, then you should change your `package.json` so that `typescript` is at least version `2.8.1` (that is the minimum TypeScript version we support).

**Comment by drfbwilliams** [comment]
Bit long in the day here, but I see these errors are still showing in React. 

These errors are appearing from sample source on your site, specifically stating typescript support.

Any updates?

Cheers
